services:
  redis:
    image: redis:7.2.5-alpine
    container_name: redis
    env_file: .env
    restart: unless-stopped
    networks:
      - datahub
    volumes:
      - redis-data:/data
    command: sh -c "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  datahub-api:
    build:
      context: ../../
      dockerfile: infra/DockerFile
    container_name: datahub-api
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "3000:80"
    networks:
      - datahub

networks:
  datahub:

volumes:
  redis-data:
